- gulpfile.js
- package.json
- src/print.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/3)
> Add jscs stylish to build process

- .jscsrc
- gulpfile.js
- package.json
- src/index.js
- test.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/7)
> Basic ESRI loader

- .jshintrc
- src/index.js
- src/layer.js
- test.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/9)
> Basic layers module

- .travis.yml
- package.json
- spec/projSpec.js
- spec/support/jasmine.json
- src/index.js
- src/proj.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/26)
> Projection module

- src/attribute.js
- src/index.js
- src/layer.js
- testAttribute.html
add functions to load attributes from ESRI Feature and Dynamic Map Service Layers
Closes #23, #24, #25
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/33)
> feat(geoApi): add attribute loader module

- src/attribute.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/37)
> refactor(geoApi): adopt arrow functions

- src/attribute.js
- src/shared.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/39)
> refactor(geoApi): create common function module

- package.json
- src/index.js
- src/mapManager.js
- test.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/42)
> Map module updates

- src/index.js
- src/layer.js
Expose image server layer object for use by app
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/44)
> feat(geoApi): imager server layer support

- gulpfile.js
- package.json
- spec/mapManagerSpec.js
- src/index.js
- src/mapManager.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/46)
> Proxy support

- src/attribute.js
Added helper properties to make it easier for app to work with attribute results.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/49)
> feat(geoApi): helper properties on attribute bundle

- .travis.yml
- package.json
- spec/geojsonTestPoint.json
- spec/projSpec.js
- src/proj.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/50)
> GeoJSON Projection

- package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/52)
> chore(build): bump version to 0.3.0

- src/events.js
- src/index.js
- testEvents.html
Added wrapper module for dojo events.
closes #28 
Unit tests to follow
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/51)
> Wrap events

- package.json
- src/index.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/56)
> Fix for multiple define bug

- package.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/59)
> Weekly sync

- spec/eventSpec.js
closes #28
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/62)
> test(events): add events unit tests

- src/layer.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/65)
> Expose tile dependency

- src/index.js
- src/layer.js
- testIdent.html
Identify function for Dynamic Layers
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/66)
> feat(layer): server side identify

- src/index.js
- src/mapManager.js
- testBasemap.html
- testScalebar.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/67)
> add overview map to geoApi: See testScalebar.html for demo

- src/proj.js
add isSpatialRefEqual
fix projectEsriExtentBuilder via rename EsriExtent to Extent
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/73)
> full extent related changes

- package.json
- src/layer.js
- testDynamicGeo.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/75)
> Dynamiclayer

- src/index.js
- src/layer.js
Just exposing a class needed to handle feature layer drill-through identify
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/77)
> feat(layer): expose ESRI query

- spec/mapManagerSpec.js
- spec/projSpec.js
- src/basemap.js
- src/mapManager.js
added helper function to create Extent from extent settings.
update config settings to match v1.1
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/76)
> config related update

- masterUpdate.sh
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/82)
> Sync script

- package.json
Weekly build thing
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/83)
> chore(build): version 0.7.0

- masterUpdate.sh
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/84)
> chore(build): enhance script for untracked master

- src/layer.js
- testFileValid.html
basic validation of user file
* performs easy validations
* extracts fields
* extracts geometry
* returns data in more useful format (input is arraybuffer)
mocky tests coming later™
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/88)
> feat(layer): user file validation

- spec/mapManagerSpec.js
- src/basemap.js
- src/mapManager.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/90)
> Part 1: base map re-projection, full extent, overview map issue. 3rd try

- package.json
See https://github.com/blog/2111-issue-and-pull-request-templates
Opening the PR as a starting point for discussion.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/81)
> Add templates for issues and PRs

- src/index.js
- src/proj.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/93)
> chore(build): update dependencies

- package.json
- src/index.js
- src/proj.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/94)
> Exposing esri graphic stuff

- package.json
- src/index.js
- src/layer.js
Relates fgpv-vpgf/fgpv-vpgf#434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/96)
> feat(geo): expose layer drawing options

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/97)
> chore(readme): add more badges to readme.md

- src/index.js
- src/symbology.js
- testSymbols.html
Fetch symbology based on layer and object id
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/99)
> Symbology fetching

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/101)
> chore(build): update version to 0.9.0

- .jscsrc
- package.json
- src/symbology.js
- testSymbLeg.html
exposes function that converts a renderer to a legend object
unit tests come later™
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/102)
> renderer to legend

- package.json
- src/index.js
- src/layer.js
- src/ogc/ogc.js
Resolves fgpv-vpgf/fgpv-vpgf#510
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/103)
> Fix a bad if statement

- .travis.yml
- package.json
- src/mapManager.js
In support of fgpv-vpgf/fgpv-vpgf#151.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/104)
> Expose map defaults from esri config

- spec/zoomSpec.js
- src/mapManager.js
- src/symbology.js
- testZoomLevel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/107)
> find closest zoom where layer is visible

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/108)
> Update to v0.10.0

- gulpfile.js
- spec/projSpec.js
- src/layer.js
- src/layer/bbox.js
Fixes an issue blocking fgpv-vpgf/fgpv-vpgf#413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/111)
> Bbox reprojection fixes

- package.json
- src/attribute.js
- src/index.js
- src/layer.js
Pull scale level to support scale dependency in viewer (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/552).
Add in geometry type, as was same block of code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/112)
> feat(attributes): scrape scale and geometry

- src/layer.js
Small correction in logic in preparation for user import wizard
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/113)
> fix(layer): dont map featureservice to dynamic

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/114)
> chore(build): version 0.11.0

- spec/projSpec.js
- src/proj.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/117)
> Single point reprojection

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/122)
> chore(build): version 0.12.0

- spec/projSpec.js
- src/proj.js
Closes fgpv-vpgf/fgpv-vpgf#742 (will need a viewer update to point to a new geoApi build)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/125)
> WKT Support

- spec/projSpec.js
- src/proj.js
Add an optional callback to `checkProj` and allow it to load projections it doesn't find.
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/736
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/126)
> Projection Lookup Support

- package.json
- src/layer.js
In support of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/770
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/128)
> feat(layer): calculate smartdefaults for csv import

- package.json
- src/attribute.js
- test/testAttribute.html
fgpv-vpgf/fgpv-vpgf#685
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/129)
> Allow for reloading promise if it fails

- package.json
- src/mapManager.js
- test/testScalebar.html
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/694
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/130)
> Properly hide overviewmap

- package.json
- src/layer.js
In support of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/770
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/131)
> Add smart defaults to service-based feature layer

- package.json
Part of the viewer 1.0 build fgpv-vpgf/fgpv-vpgf#859
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/135)
> Release Candidate

- src/layer/ogc.js
When trying to get wms capabilities, makes a second call in case the first fails.
Relates to #702
Closes #908
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/136)
> fix(ogc): try get capabilities again if the first try fails

- package.json
- src/index.js
- src/symbology.js
- test/testSymbLeg.html
since IE will process in-string html tags as real tags, change SVG strings to be encoded
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/137)
> Encode SVG to base64

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/146)
> chore(build): version 1.0.2

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/148)
> chore(build): version 1.0.3

- package.json
- src/index.js
- src/query.js
- test/testQuery.html
New public function to support spatial queries against layers
In support of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/822
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/149)
> Query by geometry

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/152)
> chore(build): version 1.0.4

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/154)
> chore(build): version 1.0.5

- package.json
- src/index.js
- src/mapPrint.js
- test/testMapPrint.html
Closes #1157, #1160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/156)
> feat(print): Create Map Image from Print Service and user added layer

- package.json
- src/layer.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1166
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/158)
> Set geometry type on file layer

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/159)
> chore(build): version 1.0.6

- src/mapPrint.js
in IE and Firefox
Closes fgpv-vpgf/fgpv-vpgf#1324, fgpv-vpgf/fgpv-vpgf#1307, fgpv-vpgf/fgpv-vpgf#1306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/167)
> fix(export): correct svg xml so renders on canvas

- package.json
- spec/mapManagerSpec.js
- src/basemap.js
- src/legend.js
- src/mapManager.js
- src/mapPrint.js
- test/testBoundary.html
Extent check and adjustment (stolen from RAMP1).
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/166)
> extent boundary check

- spec/legendSpec.js
- src/legend.js
Closes fgpv-vpgf/fgpv-vpgf#1370
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/169)
> Legend Section Allocation Fix

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/171)
> Have Travis validate docs on every build

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Add nice templates to geoApi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/172)
> GitHub Templates

- src/mapPrint.js
Setting viewbox to '0 0 0 0' to normalize was hiding everything. Now, if the viewbox is missing, it's set to the svg element size.
Eyeballing.
Source comments.
Relates fgpv-vpgf/fgpv-vpgf#1463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/174)
> fix(export): viewbox set correctly on svg layers

- src/layer/ogc.js
Closes #1550
Tested with own script, did not include since this is a minor change
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/179)
> fix(bug): no longer appends url if parameters exist

- package.json
Version bump for fgpv RC3
nay
nay
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/181)
> chore(build): version 1.1.2

- package.json
- src/symbology.js
Solve a problem added from my PR review
Close #1600
Chrome, FF and Safari
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/182)
> fix(symbol): svg size is too big when undefined

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/186)
> chore(build): version 1.1.4

- package.json
- src/symbology.js
- test/testTileLegend.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/187)
> Update master to v1.1.4

- package.json
Release to v1.1.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/190)
> chore(build): version 1.1.5

- package.json
- src/proj.js
- test/testGeomProj.html
Add utm defs to proj4
Added sample in testGeomProj.html
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/192)
> feat(proj): add utm defs to proj4

- src/layer/layerRec/basicFC.js
- src/layer/layerRec/dynamicFC.js
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/layerRecord.js
- test/lr/testDLayer3.html
- test/lr/testDLayer4.html
- test/lr/testFLayer.html
Remove promises from scale functions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/195)
> Scale is synchronous

- src/attribute.js
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/shared.js
- test/lr/testDLayer.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/196)
> No more attribute crawl

- package.json
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/layerRecord.js
- src/layer/layerRec/main.js
- test/lr/testFLayerMap2.html
- test/lr/testFLayerMap3.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/197)
> Feature Identify and Synchro Feat Names

- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/featureRecord.js
- test/lr/testDLayerMap4.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/198)
> Filter dynamic identify

- package.json
- src/attribute.js
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/layerInterface.js
- test/lr/testDLayerMap4.html
- test/lr/testFLayerMap2.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/200)
> Get Feature Name

- spec/attributeSpec.js
Add unit tests for attribute
Yes, code is comprised of unit tests
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/201)
> Attribute unit tests

- package.json
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/layerRecord.js
- src/layer/layerRec/shared.js
- src/layer/layerRec/wmsRecord.js
- test/lr/testDLayerMap4.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/202)
> Identify requestor object

- spec/querySpec.js
Add unit tests for query
Yes, all of the codes are part of unit tests
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/199)
> test(query): add unit tests for query

- package.json
- src/layer/layerRec/layerInterface.js
- test/lr/testDLayer.html
- test/lr/testDLayerMap.html
- test/lr/testFLayer.html
- test/lr/testFLayerMap.html
- test/lr/testWLayer.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/203)
> Attribs to details on proxy

- src/layer/layerRec/wmsRecord.js
- test/lr/testWLayerMap.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/205)
> WMS Enhance

- spec/hilightSpec.js
- spec/ogcSpec.js
Add unit tests for hilight
Yes
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/204)
> Add tests for hilight and ogc

- spec/basicFCSpec.js
- spec/dynamicFCSpec.js
- spec/symbologySpec.js
Add unit tests for symbology
Yes, code is comprised of unit tests
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/206)
> Symbology unit tests

- spec/wmsFCSpec.js
- src/layer/layerRec/wmsFC.js
Add unit tests for wmsFC
Yes, code is comprised of unit tests
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/207)
> WmsFC unit tests

- spec/hilightSpec.js
- spec/ogcSpec.js
- spec/querySpec.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/210)
> refactor some of the files in spec

- spec/attribRecordSpec.js
- spec/layerRecordSpec.js
- spec/tileRecordSpec.js
- src/layer/layerRec/layerRecord.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/211)
> Add unit tests for record files

- spec/featureRecordSpec.js
- spec/imageRecordSpec.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/213)
> Add unit tests for featureRecord and imageRecord

- spec/layerRecordSpec.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/214)
> delete a console log and add a default id to the esri layer when created 

- spec/attribRecordSpec.js
- spec/imageRecordSpec.js
- spec/layerRecordSpec.js
Refactor some of the record files 
Yes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/215)
> Refactor some of the record files 

- package.json
- src/layer/layerRec/featureRecord.js
- test/lr/testDLayerMap7.html
- test/lr/testJLayerMap.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/216)
> File layers has null url

- package.json
- src/layer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/220)
> Missing lib, update dsv

- src/layer/layerRec/attribFC.js
- src/layer/layerRec/attribRecord.js
- src/layer/layerRec/basicFC.js
- src/layer/layerRec/dynamicFC.js
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/imageRecord.js
- src/layer/layerRec/layerRecord.js
- src/layer/layerRec/placeholderFC.js
- src/layer/layerRec/root.js
- src/layer/layerRec/shared.js
- src/layer/layerRec/wmsFC.js
- src/layer/layerRec/wmsRecord.js
You have no idea
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/225)
> JSDoc Executive Funboat

- src/layer/layerRec/layerInterface.js
- test/lr/FeatureLR1.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/226)
> IsOffScale on Proxy

- package.json
- src/map/esriMap.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/228)
> Expose setMapCursor

- package.json
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/attribRecord.js
- src/layer/layerRec/basicFC.js
- src/layer/layerRec/dynamicFC.js
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/layerInterface.js
- src/layer/layerRec/layerRecord.js
- src/map/esriMap.js
- src/shared.js
- test/lr/DynamicMap2.js
- test/lr/FeatureMap1.js
- test/lr/FeatureMap2.js
- test/lr/FeatureMap3.js
Add support for zoom to graphic.
Some extra bug fixes as well.
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1959
Four runnable tests with different geometry and scale situations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/231)
> zoomToGraphic

- package.json
- src/symbology.js
Made symbology lookup respect custom delimiter for unique value renderers
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2034
Tested against application
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/232)
> Respect UVR Delimiter

- spec/dynamicFCSpec.js
- spec/featureRecordSpec.js
- spec/projSpec.js
- spec/wmsFCSpec.js
Fix failing unit tests and make the proj4 tests pending.
Yes, code is comprised of unit tests.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/233)
> Post webpack unit tests

- package.json
Point to new version of `shapefile-js` for webpack compatibility
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2037
Loaded shapefiles in the viewer
A lovely readme in the new library repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/234)
> New shapefile library

- package.json
- src/layer/layerRec/layerInterface.js
- src/layer/layerRec/layerRecord.js
- src/layer/layerRec/placeholderFC.js
- test/lr/DynamicLR1.js
- test/lr/FeatureLR1.js
In support of grid filter logic.  When using a proxy to a source with attributes, need to know if it's living in a dynamic or a feature layer.
Test files updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/235)
> parentLayerType property

- package.json
- src/map/esriMap.js
Expose `toMap` on the map for my good pal Miles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/236)
> Expose toMap

- package.json
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/layerInterface.js
- test/lr/DynamicLR1.js
- test/lr/FeatureLR1.js
Support for datagrid query parameters
Two real tests - dynamic child and feature layer
Fancy comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/237)
> queryUrl property

- package.json
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/layerInterface.js
- test/lr/DynamicLR1.js
- test/lr/FeatureLR1.js
In support of bounding box tracking
Two tests updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/238)
> proxy itemIndex property

- package.json
- src/layer/layerRec/attribRecord.js
Additional change to shapefile library for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2037
Local test against viewer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/239)
> Adjust shapefile lib

- src/layer/ogc.js
Closes fgpv-vpgf/fgpv-vpgf/issues/2054.  Fix the issue when service does not respond while importing service layers in IE11.
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/240)
> Fix the error on IE when importing a rest service

- package.json
- src/layer.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2096
Changed promise declaration to prevent asynch code from running too early.
Against application. Files loaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/241)
> JSON File Promise Order

- package.json
- src/attribute.js
- src/layer/layerRec/dynamicRecord.js
- src/symbology.js
Additional fix towards https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1736
Corrected use of array index for Dynamic LayerInfos
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2162
Changes case of renderer fields to match fields list
Loaded problem layers in viewer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/244)
> Dynamic Child Indexes and Renderer Fields

- package.json
- src/layer.js
- src/symbology.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2177
Chills out if no properties are in a json file
Loaded a bunch of files, including a no property file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/245)
> No property json file

- package.json
- src/proj.js
Quick fix for issues related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2234
Doing this to support forest-fires.
Tested against application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/248)
> Hardcode esri projection

- package.json
- src/map/esriMap.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2182
Allows overriding the basemap used in the overview map
Tested against the app
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/249)
> Custom overview map

- spec/attributeSpec.js
- spec/dynamicFCSpec.js
- src/layer.js
As title and also get rid of the errors when running unit tests
Relating to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2254, https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2230
Yes
Some spec files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/250)
> Strengthen validation for CSV files

- package.json
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/attribRecord.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2282
If a functiony field name is found, adds a matching function that returns the field value to chill out the datagrid.
Tested against sample file.  Even in IE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/252)
> Handle functiony field names

- src/layer.js
Closes fgpv-vpgf/fgpv-vpgf#1856
IE and chrome
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/254)
> fix(layer): reject csv files with duplicate column names

- package.json
- src/attribute.js
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/layerInterface.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/613,  https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2284
Local hack testing. Plus Alex seemed pleased with it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/255)
> feat(attribute): count and abort att load

- package.json
- src/map/esriMap.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2214
Tested with a map
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/256)
> Fit map to extent

- package.json
- src/layer.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/868
As title 
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/257)
> Allow user to import poorly named files

- package.json
- src/layer/layerRec/layerInterface.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2273
Fixes a silly mistake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/258)
> Return zoom promise

- package.json
- src/layer.js
- test/testUrl.html
Treat importing files and services differently
Relates to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/868
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/259)
> Separate importing logic for files and services

- package.json
- src/layer/layerRec/featureRecord.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2120
Applies a filter to a feature layer at layer creation time
Barry did good tests, I have no doubt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/263)
> Pre-filter on featurelayer

- spec/attribRecordSpec.js
- spec/attributeSpec.js
- spec/dynamicFCSpec.js
- spec/esriMapSpec.js
- spec/imageRecordSpec.js
- spec/layerRecordSpec.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2359.  As title.
Yes, I have run `npm run test`
Unit tests as known as `*Spec.js`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/264)
> Fix broken unit tests

- spec/attribFCSpec.js
- spec/hilightSpec.js
- spec/layerSpec.js
- spec/projSpec.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2359.  As title.
Yes, I have run `npm run test`
Unit tests as known as `*Spec.js`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/264)
> Fix unit tests for 2.1.0

- package.json
- spec/attribFCSpec.js
- spec/attributeSpec.js
- spec/dynamicFCSpec.js
- spec/hilightSpec.js
- spec/layerSpec.js
- spec/projSpec.js
- src/attribute.js
- src/hilight.js
- src/layer.js
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/attribRecord.js
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/layerInterface.js
- src/layer/layerRec/layerRecord.js
- src/map/esriMap.js
- src/proj.js
- test/testUrl.html
Putting `v2.1.0` branch onto develop `branch`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/267)
> v2.1.0 rebase

- src/layer.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2422
As title, round values to at most 6 digits after the decimal place if needed.
Manually and please see https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2422 for more info related to testing
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/269)
> Round values for csv if needed in validation

- package.json
- src/symbology.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2420
Take the the original size and multipy it by 1.33333 then round it to an integer 
Use tag `v2.1.0-16`
Try http://geoappext.nrcan.gc.ca/arcgis/rest/services/NEB/Incident/MapServer/0
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/270)
> Increase size of legend symbols

- package.json
- src/attribute.js
- src/layer/layerRec/shared.js
- src/symbology.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2368
Derives SQL WHERE snippets for legend symbols to allow them to be filtered via definition queries.
Lots of tests against real layers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/271)
> Symbology Query Strings

- package.json
Updates version number for `v2.1.0` release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/273)
> v2.1.0 release

- package.json
- src/attribute.js
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/layerRecord.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1345
No existing tests failed :+1: 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/276)
> Support for timed layer refreshing

- package.json
- src/layer/layerRec/featureRecord.js
Exposes feature attributes on the maptip event. Allows extensions / fancy code to generate maptip content that is more than just feature name
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2527
I trust this one line change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/278)
> Expose attribs on maptip event

- package.json
- src/symbology.js
Add a bracket in the else clause of defaultSymbol.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/281)
> Ensure proper format of the definition clause of defaultSymbol

- package.json
- src/symbology.js
Fixes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2590
Tested using the [service](http://geoappext.nrcan.gc.ca/arcgis/rest/services/MMS/IMA_F/MapServer/0/) from the issue, and also a [service](http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_AirEmissions_CO/MapServer/0) that uses integer keys for unique value filter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/283)
> Encode single quotes in filters

- package.json
- src/map/basemap.js
- src/map/esriMap.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/497, https://github.com/fgpv-vpgf/fgpv-vpgf/issues/107.
`npm run test`
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/289)
> Initial basemap load fail - supporting PR

- package.json
- src/layer.js
- src/layer/layerRec/dynamicRecord.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2544.
`npm run test`
In-line comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/291)
> fix(identify): ignore filtered out features for dynamics

- package.json
Update version tag to 2.3.0
NA
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/293)
> Update version tag to 2.3.0

- package.json
- src/proj.js
Fixes build issue with webpack 4 wrt PR https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2708. This should be merged and tagged followed by https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2708.
Local build and serve of dev and prod. Working link http://fgpv.cloudapp.net/demo/users/milesap/update-deps/dev/samples/index-samples.html
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/295)
> fix(proj4): revert proj4 to commonJS loading for webpack 4 compatibility

- package-lock.json
- package.json
Lock file missed, added new babel preset env.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/296)
> chore(build): add missing dep

- package-lock.json
- package.json
- src/map/basemap.js
- src/map/esriMap.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2699.
Allows for adding / removing of basemaps from gallery.
`npm run test`
JSDoc, in-line comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/297)
> Api 12 helper (BasemapGroup, Basemap)

- package.json
- src/layer/layerRec/attribRecord.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2684 - idea 1 implemented.
:eyes:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/302)
> feat(identify): add fieldname to details element

- package.json
Update version to 2.4.0 for release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/304)
> Update version to 2.4.0 for release

- package.json
- spec/featureRecordSpec.js
- src/layer.js
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/layerRecord.js
- src/layer/layerRec/shared.js
- src/layer/layerRec/wmsRecord.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2748
Yes! I changed one test!
JSDoc, In-line comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/303)
> Supporting PR for WFS layers

- package-lock.json
- package.json
- src/agol.js
- src/index.js
Closes #2784
Created a getToken function to get credential and a getItem functiojn to get info for an agol id
With my Agol account inside the the authoring tool
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/306)
> feat(agol): get json information about web app and web map

- package.json
- src/symbology.js
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1298
:eyes: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/307)
> feat(ui): changes to help symbology expand large images

- package.json
- src/map/esriMap.js
relates fgpv-vpgf/fgpv-vpgf#2833
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/312)
> feat(map): add CORS hack to layer URLs

- package.json
- src/layer/layerRec/graphicsRecord.js
- src/symbology.js
Adding styles to the render options
:eyes:
see [fgpv PR](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2824)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/309)
> feat(layer): add style options for points, lines, and polygons

- package.json
- src/layer/layerRec/wmsRecord.js
relates fgpv-vpgf/fgpv-vpgf#331
would need to mock too much of the ESRI API to validate a simple object set
jsdoc
- n/a `gulp test` succeeds without warnings or errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/315)
> feat(wmsRecord): add custom parameter setter

- package.json
- spec/esriMapSpec.js
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/attribRecord.js
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/featureRecord.js
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2866
Fixed up broken unit tests (from before)
In-line comments, JSDoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/316)
> Support for dynamic layer configurable display field

- package-lock.json
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2578. Similar to this PR on viewer repo: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2887
None that I know of, Travis build generated successfully with updates made. 
Not applicable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/318)
> fix(package): update marked to v4.0

- package.json
- src/map/esriMap.js
Closes #2967
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/323)
> fix(overview): tileSchema overviewUrl not working

- package.json
- src/symbology.js
Helps https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3049
:eyes: see viewer PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/330)
> fix(symbology): fix queries where min and max are equal

- package-lock.json
- package.json
- src/shared.js
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3044
The `A` in `Anonymous` should be an `a`
tested with ramp printing
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/331)
> Local JS printing helper

- package-lock.json
- package.json
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/attribRecord.js
- src/layer/layerRec/basicFC.js
- src/layer/layerRec/dynamicFC.js
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/filter.js
- src/layer/layerRec/graphicsRecord.js
- src/layer/layerRec/layerInterface.js
- src/layer/layerRec/layerRecord.js
- src/layer/layerRec/root.js
- src/layer/layerRec/shared.js
- src/layer/layerRec/wmsRecord.js
- src/query.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3237
Implements the bulk of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3227
And aligns with https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3082
Primarily this PR implements a new filter system on the layers.  Highlights include:
* centralized filter status on all feature class objects of feature-based layers
* on-map filter support for file/wfs based layers
* cleaned up event throwing in geoApi
Tests run against viewer. Will continue to test after integrating with grid plugins.
JS Docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/336)
> Updated filter engine

- package-lock.json
- package.json
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/featureRecord.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3331
Fixes two bad variable references
Local test. Failing sample now works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/341)
> Typeo in feature zoom

- package-lock.json
- package.json
- src/layer/layerRec/attribFC.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3379
Local testing. Related viewer PR will allow testing against actual layer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/342)
> Properly encode sr on web call

- README.md
- package-lock.json
- package.json
- src/index.js
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/attribRecord.js
- src/layer/layerRec/basicFC.js
- src/layer/layerRec/dynamicFC.js
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/featureRecord.js
- src/layer/layerRec/filter.js
- src/layer/layerRec/graphicsRecord.js
- src/layer/layerRec/layerInterface.js
- src/layer/layerRec/layerRecord.js
- src/layer/layerRec/root.js
- src/layer/layerRec/shared.js
- src/layer/layerRec/wmsRecord.js
- src/map/esriMap.js
- src/query.js
Pulling the `ver3` branch onto `develop`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/344)
> Ver3 branch --> Develop branch

- .travis.yml
- package-lock.json
- package.json
- spec/layerRecordSpec.js
- spec/querySpec.js
- src/layer/layerRec/attribRecord.js
- src/layer/layerRec/layerRecord.js
- src/layer/layerRec/shared.js
Supports fix for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3515
Removed broken tests; they are being fixed in Ryan's PR.
None
- ~~[ ] `gulp test` succeeds without warnings or errors~~
- ~~[ ] release notes have been updated~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/348)
> fix(layerRecord): move filter listeners to layerRecord

- package-lock.json
- package.json
- src/layer/layerRec/filter.js
Minting the `v3.0.0` version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/351)
> version bump

- package-lock.json
- package.json
- src/layer/layerRec/attribFC.js
- src/layer/layerRec/attribRecord.js
- src/layer/layerRec/dynamicRecord.js
- src/layer/layerRec/featureRecord.js
Implements https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/350)
> feat(attribs): add support for field alias definitions

- package-lock.json
- package.json
- src/query.js
fgpv-vpgf/fgpv-vpgf#3651
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/352)
> fix(attrib): fix special chars applying filters to map

- package-lock.json
- package.json
- src/query.js
Issue: fgpv-vpgf/fgpv-vpgf#3647
Plugins PR: fgpv-vpgf/plugins#120
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/353)
> fix(attrib): handle specific % case for map filters

- package-lock.json
- package.json
Bumping version so the build behaves itself
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/358)
> version bump to appease npm

- package-lock.json
- package.json
Enhance the version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/359)
> gapi version bump

- package-lock.json
- package.json
- src/layer.js
- src/layer/layerRec/attribFC.js
- src/layer/ogc.js
- src/map/basemap.js
- src/map/esriMap.js
- src/proj.js
- src/query.js
Adds support for WKT projections, and fixes code that previously demanded WKID only.
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3442
See best friend PR https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3748 for big list of tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/360)
> Support for wkt projections

- README.md
Long live the old geoApi repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/363)
> docs(repo): readme update
