src/attribute.js
src/layer.js

Store fields so we can use aliases and leverage data types if needed. 
Bonus enhance to identify default, as 5 is more forgiving than 2.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/85)

feat(attribute): store field data

---

src/index.js
src/proj.js

exposing [method](https://developers.arcgis.com/javascript/jsapi/esri.graphicsutils-amd.html#graphicsextent) that converts graphics into extent for use in zoomToGraphic in geoService.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/91)

feat(geo): exposing graphics method in proj

---

package.json
src/layer.js

Return type change to help user understand if layer predictor errored or was just confused.  In support of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/611
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/115)

feat(layer): error value on crashed predict

---

package.json
src/layer.js

`fromCharCode` function would blow up if more than 65,500 bytes were fed to it.  Switched to `TextDecoder`.  In support of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/611
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/116)

fix(layer): prevent utf8 overflow

---

spec/layerSpec.js
src/layer.js

Adds default source projection for GeoJSON.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/118)

Source Projection Defaults

---

package.json
src/layer.js

Pulls sublayer info for dynamic layers.
Additional check in case ESRI hint is wrong hint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/121)

feat(layer): layer info for dynamics

---

package.json
src/index.js
src/layer.js
test/testFileLoad.html

Allows caller to set symbol colour for file layers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/133)

Colour option for file layers

---

package.json
src/attribute.js
src/symbology.js
test/testFileLoad.html

Handle missing outlines on symbols (was occurring in CSV layers).
Add correct value to `layerId` in renderer-generated legends, to support icons showing in layer selector
Closes (in part) https://github.com/fgpv-vpgf/fgpv-vpgf/issues/867
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/134)

File Symbology upgrades

---

package.json
src/attribute.js
test/testAttribute.html

Store information about the sublayer type in the attribute data bundle.
Useful for client so it can handle non-feature based sublayers without crashing
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/140)

Layer type stored in attrib data

---

package.json
src/layer/ogc.js
test/testWmsParse.html

Supports WMS Legends where layer infos use a nested structure.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/951
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/141)

Crawl nested wms infos

---

package.json
src/attribute.js
test/testAttribute.html

Utilize the `exceededTransferLimit` flag for 10.1+ servers, thus avoiding the max count bug.
Changed parameters on recursive scraping function to use an option object instead.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/142)

Handle attribute count on bad servers

---

package.json
src/symbology.js
test/testSymbols.html

Allow class breaks symbol search to work with target values in string format.
Also corrects a mistake where code was looking for a client-side object property on a server-side object.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/948
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/143)

Class breaks renderer fix

---

package.json
src/layer.js

Return group layer as a dynamic layer
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/929
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/145)

add group layer handler

---

package.json
src/layer.js

Latest update to terraformer no longer accepts 0 as an object id. 
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/147)

Use proper oids for files

---

package.json
src/symbology.js

applies mostly to file-based layers
Relates fgpv-vpgf/fgpv-vpgf#1206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/153)

fix(layer): add default symbology outline if one is missing

---

package.json
src/mapManager.js
test/test.html
test/testAttribute.html
test/testBasemap.html
test/testDynamicGeo.html
test/testEsri.html
test/testEvents.html
test/testFileLoad.html
test/testFileValid.html
test/testGeomProj.html
test/testHilight.html
test/testIdent.html
test/testQuery.html
test/testScalebar.html
test/testSymbols.html
test/testUrl.html
test/testZoomLevel.html

Moved `findClosestLOD` function from application geo module to the geoApi.  Function searches an LOD array to find LOD closest to the provided scale.
Also updated test page references to not use the minified library, as it is not generated unless you add extra flags to the serve command
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/157)

LOD scale search

---

package.json
src/mapPrint.js
test/testMapPrint.html

also, render an image for __all__ vector layers locally on the client since it's faster
Relates fgpv-vpgf/fgpv-vpgf#1267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/161)

feat(export): return local and server based images as separate promises

---

package.json
src/mapPrint.js
src/shared.js
src/symbology.js
test/testMapPrint.html
test/testSymbLeg.html

Closes fgpv-vpgf/fgpv-vpgf#1279
Out of three WMS layers in `index-one` page, only "Groundwater Information Network" layer is not CORS-enabled and its legend images will taint the export canvas preventing it from saving directly. Legends for "Railways" and "Grounwater" WMS layers can be saved directly as part of the map export image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/164)

1279 fix wms tainted canvas laundering

---

package.json
src/symbology.js

Before: datatable cannot load when graphicKey value is set to null
After: set graphickey to an empty string when graphicKey is null so the
datatable can load properly.
Closes #1184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/165)

feat(geoApi): add management of null graphickey value

---

src/mapPrint.js

Note: scale preservation is turned off, otherwise the extent chagnes
depending on the image size  Relates fgpv-vpgf/fgpv-vpgf#1258
No demo for this yet.
Eyeballing tests done. Unit tests are hard due to the need of a DOM.
Source comments updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/170)

feat(export): can specify the export image size

---

src/mapPrint.js

Resizing svg images fails in Firefox because it returns `null` for the viewBox values if the viewBox is not set explicitly (Chrome properly returns "0 0 0 0").
Eyeballing as unit testing map print is hard.
Source comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/173)

fix(export): set viewbox on svg layers if absent

---

package.json
src/index.js
src/legend.js
src/symbology.js
test/testServerLegend.html

Adds server legend to client legend support. In geoApi to ensure proxy is used.
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1487 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1525
Test file to test actual code. Unit tests against mocked code later.
JsDoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/178)

Server legend support

---

src/symbology.js

Replace undefine symbol by empty svg so we not have undefnied inside filters panel for symbol
Visual
Inline
- [] release notes have been updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/180)

fix(filter) show undefined when bad renderer

---

src/symbology.js
test/testTileLegend.html

Adds a function `mapServerLegendToRendererAll` which is called when no `layerIndex` is provided to `mapServerToLocalLegend` for legend generation.
testTileLegend.html
jsDoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/185)

feat(legend): Add support for tile layers

---

package.json
src/mapManager.js

No rotation for north arrow when we export map with mercator projection
Closes #1779
Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/188)

fix(export): web mercator map should not rotation for north arrow

---

package.json
src/events.js
test/testEvents.html

Closes #1858
When we create a evant, it is return to the caller so we can access it to e.g. remote it.
In testEvents.html
Inline
- [***no release note tag for 1.1.6-1***] release notes have been updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/191)

fix(events): add return event object to access it from outside

---

package.json
src/symbology.js

Add two exported functions to convert config-supplied symbology lists.
Nope.
Inline comments.
- ~~[ ] release notes have been updated~~ not needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/209)

feat(symbology): process config-supplied symbology

---

test/sample-test-layer-map-4.js

- Change main property of geoApi's package.json to test/sample-test-layer-map-4.js
- Run the serve command from within fgpv:     npm run serve -- --env.geoLocal
- Open browser to http://localhost:6001/build/samples/blank.html
Note that the error "Uncaught TypeError: (0 , _geoApi2.default) is not a function" can be ignored for now, this is the the viewer failing to load geoApi which is now a test. I'll clean this up on the next update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/218)

add sample test to show new style requirements for webpack

---

src/layer/layerRec/basicFC.js
src/layer/layerRec/dynamicFC.js
src/layer/layerRec/dynamicRecord.js
src/layer/layerRec/layerRecord.js
test/lr/DynamicLR3.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1958
If a group of a dynamic layer is updating visibility, don't cause the layer to reload until all child updates have been processed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/229)

Use Timeout to Prevent Cascading Visibility Refreshes

---

package.json
src/layer.js
src/layer/layerRec/featureRecord.js

Handles spaces in field names for CSV files, in support of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1856 and something Johann is doing in the grid.
No longer attempts to load files residing on web servers, in support of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2061
Tested against application. Loading layers and files. Loading CSV files that are normal, have field spaces, have field spaces that collide with identical field with underscores.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/242)

CSV Spaces, Server File Loading

---

package.json
src/layer.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2083
Fields option not really being used the way it was intended, and not at all in the way it was designed (to provide a subset of fields). Easiest option for now is to remove it. 
Against app. Loaded all three flavours of files. Ensured original object id was preserved under new name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/243)

Remove custom file fields option

---

package.json
src/layer/ogc.js

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2196
Strips decimals from screen co-ords.
Did a WMS. Saw stuff come back
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/246)

Remove decimals from wms point

---

package.json
src/layer/layerRec/dynamicRecord.js
src/layer/layerRec/layerRecord.js
src/layer/layerRec/shared.js
src/proj.js

Closes
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1650
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2259
Detects incoming layer extents in lat long that are so close to the boundary that it causes math issues upon reprojection, and pushes them in a little bit.
Tested on viewer against layers identified in the issues.
Also did an offscale test using CESI layers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/251)

Handle Massive Lat Long Extents

---

package.json
src/attribute.js
src/hilight.js
src/layer/layerRec/attribFC.js
src/layer/layerRec/attribRecord.js
src/layer/layerRec/dynamicRecord.js
src/layer/layerRec/featureRecord.js
src/layer/layerRec/layerInterface.js
src/layer/layerRec/layerRecord.js
src/map/esriMap.js

`fetchGraphic` will now only get the information it requires. Caching is split across attributes and geometry.
For lines & polygons, geometry is simplified to the current scale level. The geometry cache also indexes by scale level.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2190
Helps mitigate issues in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2293
Tested against real data.
jsdoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/260)

fetchGraphic performance upgrade

---

package.json
src/layer.js
src/proj.js

Supports item 1 of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2234
Updated projection lookup to consider the `latestWkid` field, if available, and with priority (as it often is the EPSG code rather than the ESRI code).
Removed similar projection management code from geoJson loader.
Tested against various layers
- files
- files with defined with projections
- services with known projections
- services with unknown projections
- services with unknown projections with latestWkid
- reloading services with unknown projections (verified cached projection was used)
jsdoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/261)

latestWkid support

---

package.json
src/attribute.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2352
Some feature layer services appear to not mark which field is the object id. Made a change to recognize when this happens, and if so, attempt to get the object id from an alternate property.
Tested normal layer and layer without a marked oid field
jsdoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/262)

Handle unmarked objectid

---

package.json
src/layer/layerRec/dynamicRecord.js

Relates to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2364
Get the `mapName` from the service to use as the name for the top level dynamic legend entry if the name is not provided in the config
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/266)

Use mapName from service as name for a legend entry if not provided

---

package.json
spec/ogcSpec.js
src/layer/layerRec/wmsFC.js
src/layer/layerRec/wmsRecord.js
src/layer/ogc.js

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/332
Ability to change between styles for WMS layers
Yes, updated `ogcSpec`
Comments and JSDoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/268)

WMS layer additional styles

---

package.json
src/attribute.js
src/layer/layerRec/layerRecord.js

Corrects a portion of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2443
Takes into account effective scale levels on dynamic layers
Selects correct closest tile level when attempting to zoom to a visible scale beyond the basemap.
Tested against layer in issue, both in feature and dynamic mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/272)

Fix Zoom Too Far Behavior

---

package.json
src/index.js
src/layer.js
src/layer/layerRec/dynamicFC.js
src/layer/layerRec/dynamicRecord.js

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2528
Fixes problem in dynamic layer child opacity updates where value updates would erase the values of other children.
Adds ability to use layer format from layer config snippet. Default is now `png32` to give best support for child opacity
No because it affects map layers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/279)

Child Opacity and Dynamic Image Formats

---

package.json
src/layer/layerRec/attribFC.js
src/layer/layerRec/dynamicRecord.js
src/layer/layerRec/featureRecord.js
src/layer/layerRec/layerInterface.js
src/layer/layerRec/layerRecord.js

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2507.
Exposes `getAttribs` function to be used in api layers.
`npm run test` :white_check_mark: 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/280)

Api 02 helper (BaseLayer & ConfigLayer)

---

package.json
src/layer/layerRec/attribFC.js

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2507
Sets `loadIsDone` flag for file layer attributes when promise resolves.
npm run test :white_check_mark:
In-line comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/282)

Api 02 file layer fix

---

package.json
src/layer.js
src/layer/layerRec/graphicsRecord.js
src/layer/layerRec/layerInterface.js
src/layer/layerRec/main.js
src/layer/layerRec/shared.js
src/layer/layerRec/simpleRecord.js

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2588
Create a `GraphicRecord` similar to `FeatureRecord` which is used when creating `SimpleLayers` through the external API
Tested existing functionality related to `FeatureLayers` especially to ensure nothing broke and `GraphicRecord` functionality
JSDoc, in-line comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/284)

Api 06 helper (SimpleLayer)

---

package.json
src/layer/layerRec/graphicsRecord.js

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2615.
Allows for MultiLines to be added through the external API.
`npm run test`
JSDoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/287)

Api 09 helper (MultiLineString)

---

package.json
src/layer/layerRec/graphicsRecord.js

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2617.
Allows for MultiPolygons to be added through the external API.
`npm run test`
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/288)

Api 11 helper (MultiPolygon)

---

package.json
src/layer/layerRec/graphicsRecord.js
src/layer/layerRec/layerInterface.js

Apply a modified version of `zoomToGraphic` on the `GraphicRecord` class. This is a quick fix to support CIP demo. A more proper approach of adding an API zoom endpoint and cleaner code will be done later.
Added some points and polygons, did some API zooms, tried some offsets.
Use geoApi `v2.2.1-18` to test locally.
API commands for testing
```js
const aPoint = new RZ.GEO.Point('factory', 'https://image.flaticon.com/icons/svg/17/17799.svg', [-78.4, 44.6]);
const mymap = RZ.mapInstances[0];
mymap.simpleLayer.addGeometry(aPoint);
mymap.simpleLayer._layerProxy.zoomToGraphic('factory', mymap._fgpMap, {x: 0, y: 0});
```
Some nice comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Graphic zoom on graphic record

---

package.json
src/map/esriMap.js

Allows the north arrow angle to be calculated from a specified point instead of only at the bottom center. 
`npm run test`
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/298)

North arrow specify point

---

package.json
src/map/esriMap.js

Catches zoom errors or otherwise they will prevent subsequent zooms.
Closes fgpv-vpgf/fgpv-vpgf#2730
:eyes: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/301)

fix(map): catch shiftzoom errors

---

package.json
src/map/basemap.js

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2463
Allows config to target the opacity of individual tiles in a basemap collection. Allows for fancy overlays.
Tried out some modified configs. They looked lovely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/299)

Support basemap opacity per sublayer

---

package.json
src/layer/layerRec/featureRecord.js
src/layer/layerRec/layerInterface.js
src/layer/layerRec/layerRecord.js
src/layer/layerRec/placeholderFC.js

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2859
Wires in new behavior for WFS layers that originate from the config.  Will block in a `loading` state and not generate an ESRI Feature Layer.  New public function to then pass in a premade ESRI Feature Layer after the fact, wire it in, then set layer to loaded.
Tested against autopop legends, structured legends, and CCCS viewer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/313)

WFS race condition support

---

package.json
src/index.js
src/layer.js
src/layer/layerRec/wmsRecord.js

Avoids a getCapabilities call by providing a `resourceInfo` config parameter if the WMS ramp config has a property called `suppressGetCapabilities` and is set to `true`.
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/314)

feat(WMS): allow getCapabilities to be turned off

---

package.json
src/layer/layerRec/wmsRecord.js
src/layer/ogc.js

Support for CCCS.  If identify request on WMS is of mime type json, fetch the result as json, not text.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2905
Tested against CCCS layer with JSON mime type.
Tested against classic WMS with text results to ensure text still works
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/317)

Support json wms identify

---

package.json
src/defaultRenderers.json

Creates black circle outlines for default points (helpful for WFS layers). `outline` added to `circlePoint`
:eyes:
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/320)

fix(layerRecord): add outline to default points

---

package.json
src/layer.js
src/layer/layerRec/featureRecord.js
src/layer/layerRec/layerRecord.js
src/layer/ogc.js

When validating file / WFS layer data, now have the option to provide in a non-encoded format.
Also removes some hack properties from the WFS demo madness, and corrects some quotes.
Requirements driven from CCCS project
`npm run test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/321)

Support unencoded layer data

---

package-lock.json
package.json
src/map/print.js

Print map was modifying layer SVGs and causing them to be offset when the map resized.
Most prominent was print map -> fullscreen pushing features away from their proper locations.
index-samples 76 and 75
in-line
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/322)

fix(print): clone svgs in print map process

---

package.json
src/symbology.js

Closes #2965
When no symbology is associated to a layer do not apply symbolbogy
Use this layer to test: http://gis.pendercountync.gov/arcgis/rest/services/Base_Map/MapServer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/324)

fix(symbology): add annotation layer inside dynamic service

---

package.json
src/map/print.js

Detect `esriJobFailed` when printing.
Relates #2992
:eye: 
Inline comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/325)

feat(print): detect print failure

---

package.json
src/layer/layerRec/dynamicRecord.js

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2981
When Dynamic Layers in symbology stacks were identified, all symbologies in close proximity were identified (regardless if they were toggled on/off)
Test sample 46, also `keys=NPRI_CO`
inline comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/327)

fix(dynamicRecord): identify filters out invisible symbologies in stack

---

package.json
src/map/esriMap.js

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3023
Initial extent at map construction time was not being fitted to the screen. Adds the option to do that
Tested on local build with an extent known to be naughty.  Proper tests can be vetted when the sibling PR on the viewer is queued up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/328)

fix(map): respect extent fit on init extent

---

package-lock.json
package.json
src/layer/layerRec/dynamicRecord.js

Undo replacement of  `xlink:href` with `ns1:href` for Safari browsers before comparing identify result svg icons.
Closes fgpv-vpgf/fgpv-vpgf#3102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/333)

fix(safari): revert ns1 svg link fix for identify

---

package-lock.json
package.json
src/layer/ogc.js

Includes custom parameters on WMS identify calls
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3096
Tested showing & clicking regular WMS layers in standard app.
Tested the build in CCP viewer with time enabled layer, ensured the time was applied to the identify request and correct value was displayed in the viewer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/332)

Use custom params in wms identify

---

package-lock.json
package.json
src/layer/layerRec/attribFC.js
src/layer/layerRec/attribRecord.js
src/layer/layerRec/basicFC.js
src/layer/layerRec/dynamicFC.js
src/layer/layerRec/dynamicRecord.js
src/layer/layerRec/filter.js
src/layer/layerRec/shared.js

A refactor to remove specific-case function names (like `getNonGridOIDs` and `setSymbolSql`).
We can now take on any number of sql-based filters, allowing new plugins to have their own filter sets.
Added ability to exclude specific filters from key functions to.   E.g. if grid wants list of things a layer is filtering, it would exclude any grid-based filters.
Most changes are just affecting the internals of the filter object.
Tested in local build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/337)

More flexible filters

---

package-lock.json
package.json
src/layer/layerRec/attribFC.js
src/query.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3268
If we are doing an extent filter on a server-based layer, we now convert the extent to a polygon prior to sending it to the server's query endpoint.  This helps alleviate some false-positives we were encountering due to (we think) extent warping to a different projection on the server.
Tested extent filters for
- server layer in native lat-long
- server layer in native lambert
- file layer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/338)

Extent filter on off projection service

---

package-lock.json
package.json
src/layer/layerRec/graphicsRecord.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3285
Instead of reprojecting geometry one vertex at a time, we leverage the geometry projection methods in terraformer/proj4 which seem to be optimized for batch calls
Tested existing geometry creation methods using the test pages and the direct API samples in browser console.
Added a large polygon test to verify performance increase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/339)

Change how API geometry is reprojected

---

package-lock.json
package.json
src/index.js
src/layer/layerRec/attribFC.js
src/layer/layerRec/graphicsRecord.js
src/layer/layerRec/layerRecord.js
src/map/esriMap.js

Provides properties exposing inner esri classes to allow hardcore plugin developers do risky things to meet deadlines
Removed concept of `debug` switch, as it just provided an un-required extra step.
Ran the app. Verified properties and functions returned valid objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/340)

esri backdoor properties

---

package-lock.json
package.json
src/query.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3430
Adds start and end of line restrictions to the AQL query engine for the `LIKE` operator, which affects file & WFS layers.
so now filter string `LIKE '101%'`
will match `1010203`
but not match `2010103`
Tested using layers, both with lazyFilter enabled and disabled.
Proper tests can be done on the corresponding viewer PR, which will let you run ramp using this fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/345)

Aql like operator respects start and end of string

---

package-lock.json
package.json
src/layer/layerRec/dynamicRecord.js

Supports fix for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3441
Logic to mark dynamic layers with no results was referencing non-existing properties.
Tested against application (Sample 6)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/346)

Dynamic identify no result flag

---

package-lock.json
package.json
spec/attribFCSpec.js
spec/imageRecordSpec.js
spec/layerRecordSpec.js
spec/projSpec.js
spec/querySpec.js

This PR fixes many of the errors that showed up when running the command `npm run test`. Some query tests were removed for now as they are no longer useful to test.
- ~~[ ] `gulp test` succeeds without warnings or errors~~
- ~~[ ] release notes have been updated~~
- ~~[ ] has been tested in IE~~
- ~~[ ] orignal issue has been reviewed & updated to reflect the PR content~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/349)

fix(spec): fix unit test errors

---

package-lock.json
package.json
src/layer/layerRec/featureRecord.js
src/layer/layerRec/layerRecord.js
src/layer/layerRec/wmsRecord.js

Implements https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3639
Moves tracking of "first load" to inside geoApi. Exposes new property on layer records `initLoadDone`.
Removes some legacy code from CCP WFS demo panic.
Tested against
- ArcGIS Server layers
- ArcGIS Server layer initialized to invisible
- File based layers
- WFS Layers
- WMS Layers with baked capabilities
Ensured loading indicators on map and legend behaved as expected, and nothing weird was up.
Real testing available on viewer PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/354)

Track initial load internally

---

package-lock.json
package.json
src/layer.js

Closes fgpv-vpgf/fgpv-vpgf#3689 and fgpv-vpgf/fgpv-vpgf#3694
Convert LAT/LONG fields into `esriFieldTypeDouble` to be filtered and treated as numbers in plugins
Later in the viewer PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/356)

fix(attrib): fix lat/long map filtering

---

package-lock.json
package.json
src/layer/layerRec/featureRecord.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3292
If attributes of a feature layer have not been downloaded, no longer download them all when a map click / identify happens. Instead use the fast-lookup pipeline that hovertips use.
Will be testable in the viewer PR.
Tests include
- ArcGIS Server Feature Layer
- Clicking points before table has been opened. Verifying on network that only pings for clicked features are happening (no bulk downloads).
- Clicking points after table has been opened. Verifying on network that no pings or bulk downloads happen. All lookups should be from local cache.
- Clicking clusters of points that give multiple identify results
- Clicking on overlapping layers where both layers give identify results
- File layer
- Things act as always, both before and …

Smart feature identify

---

package-lock.json
package.json
src/query.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3699
When negative number filters are applied to map, there is no effect because there is no support for `Prefix` types such as `-` and `+`. Added this to `typeReactor` in `sqlNodeToAqlNode` to allow negative number filters to be applied to map. 
Later in viewer 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/geoapi/357)

feat(query): add support for Prefix for sqlToAql
